apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkxNTEyLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJaRzlqYTJWeVkzSmxaRHBEYUdGdVpHRnVZVUF4TWpNPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
